services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    pull_policy: build
    environment:
      - DATABASE_URL=sqlite:///app/data/manager.db
    volumes:
      - ./data:/app/data
      - ./server_instances:/app/server_instances
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    pull_policy: build
    ports: 
      - "80:80"