---
version: "3"
includes:
  setup:
    taskfile: ./tasks/setup.yml
    optional: true
  backend:
    taskfile: ./tasks/backend.yml
    optional: true
  certs:
    taskfile: ./tasks/certs.yml
    optional: true
  test:
    taskfile: ./tasks/test.yml
    
    optional: true
