FROM python:3.13-slim
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install uv --no-cache-dir

COPY pyproject.toml uv.lock ./
RUN uv sync --locked

COPY src/ /app/src

COPY src/start.sh ./src/start.sh
RUN chmod +x ./src/start.sh

ENTRYPOINT ["/app/src/start.sh"]